name: muffed
description: A lemmy client written in flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.8.5+14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  any_link_preview: ^3.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dynamic_color: ^1.6.5
  dio: ^5.3.0
  hydrated_bloc: ^9.1.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.1.11
  video_player: ^2.7.0
  bloc_concurrency: ^0.2.2
  flutter_animate: ^4.2.0
  flutter_markdown: ^0.6.17
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_colorpicker: ^1.0.3
  logging: ^1.2.0
  markdown_editable_textinput:
    git:
      url: https://github.com/thunder-app/markdown-editor.git
      ref: 017c8614c59b7081f54a7af70cc9586888d53b56

  lemmy_api_client:
    git:
      url: https://github.com/freshfieldreds/lemmy_api_client
      ref: 5224007fbf960f2fe2c67249f2577f798f101c3a
  cross_file: ^0.3.3+6
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  markdown: ^7.1.1
  skeletonizer: ^0.8.0
  photo_view: ^0.14.0
  matrix4_transform: ^2.0.1
  shimmer: ^3.0.0
  extended_image: ^8.2.0
  collection: ^1.18.0
  gap: ^3.0.1
  flutter_typeahead: ^5.0.1
  image_size_getter: ^2.1.2
  animations: ^2.0.10
  json_annotation: ^4.8.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  
  json_serializable: ^6.6.0

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo.svg
    - assets/placeholder_banner.jpeg
    - assets/icon.png